# ================================================
# BINARY SENSORS
# ------------------------------------------------

- platform: bayesian
  name: 'bayesian_presence_jos'
  device_class: 'presence'
  prior: 0.7
  probability_threshold: 0.9
  observations:
    - entity_id: 'input_boolean.homekit_present_jos'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'on'
    - entity_id: 'device_tracker.iphone'
      prob_given_true: 0.5
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
