# ================================================
# DEVICE TRACKERS
# ------------------------------------------------
- platform: asuswrt
  consider_home: 180
  new_device_defaults:
    track_new_devices: true
